
library(clusterProfiler)
library(AnnotationHub)
library(ensembldb)
library(tidyverse)
library(org.Hs.eg.db)
library(data.table)

gene_name <- as.data.frame(org.Hs.egSYMBOL)
gene_name$entrez <- mapIds(org.Hs.eg.db,
                           keys=gene_name$symbol,
                           column="ENTREZID",
                           keytype="SYMBOL",
                           multiVals="first")

library(fgsea)
gene_list<-fgsea::gmtPathways("../c2.cp.v7.3.entrez.gmt")

library(rlist)
kegg_name <- names(gene_list)

gene_list<-gene_list

## read maf file generated by VEP
#!/usr/bin/env Rscript
inputMAF = commandArgs(trailingOnly=TRUE)

# test if there is at least one argument: if not, return an error
if (length(args)==0) {
  stop("At least one argument must be supplied (input file).n", call.=FALSE)
} else if (length(args)>1) {
  stop("Only one input MAF file is allowed")
}

maffile<-fread(inputMAF[1],data.table = F,header = T)
### check if the columns required available from the input
required_columns<-c('Hugo_Symbol',"Variant_Classification",'SIFT','Chromosome','Start_Position','End_Position')
if(!(required_columns %in% colnames(maffile))){
  stop("At least one of the required header is not present in the input file. Please check your input file.")
}

ml_driver_input<-maffile[,required_columns]

table(ml_driver_input$Variant_Classification)
table(ml_driver_input$SIFT)

raw_length<-dim(ml_driver_input)[2]

ml_driver_input<-ml_driver_input[ml_driver_input$Variant_Classification %in% c('Frame_Shift_Del','Frame_Shift_Ins',
                                                                               'In_Frame_Del','Missense_Mutation','In_Frame_Ins',
                                                                               'Nonsense_Mutation','Silent','Nonstop_Mutation'),]

print(paste(dim(ml_driver_input)[2],"/",raw_length," mutations were kept for the analysis.",sep = ""))

ml_driver_input$Variant_Classification<-gsub('Frame_Shift_Del','4',ml_driver_input$Variant_Classification)
ml_driver_input$Variant_Classification<-gsub('Frame_Shift_Ins','4',ml_driver_input$Variant_Classification)
ml_driver_input$Variant_Classification<-gsub('In_Frame_Del','1',ml_driver_input$Variant_Classification)
ml_driver_input$Variant_Classification<-gsub('In_Frame_Ins','2',ml_driver_input$Variant_Classification)
ml_driver_input$Variant_Classification<-gsub('Nonstop_Mutation','5',ml_driver_input$Variant_Classification)
ml_driver_input$Variant_Classification<-gsub('Missense_Mutation','7',ml_driver_input$Variant_Classification)
ml_driver_input$Variant_Classification<-gsub('Nonsense_Mutation','8',ml_driver_input$Variant_Classification)
ml_driver_input$Variant_Classification<-gsub('Silent','6',ml_driver_input$Variant_Classification)

ml_driver_input$sift<-gsub("\\s*\\([^\\)]+\\)","",ml_driver_input$SIFT)
table(ml_driver_input$sift)
ml_driver_input[is.na(ml_driver_input$sift),'sift']<-'3'
ml_driver_input$sift<-gsub("deleterious_low_confidence","1",ml_driver_input$sift)
ml_driver_input$sift<-gsub("tolerated_low_confidence","2",ml_driver_input$sift)
ml_driver_input$sift<-gsub("deleterious","1",ml_driver_input$sift)
ml_driver_input$sift<-gsub("tolerated","2",ml_driver_input$sift)

#ml_driver_input$sift<-gsub("\\<//>","3",ml_driver_input$sift)
#ml_driver_input[ml_driver_input$sift==ml_driver_input[3,4],4]<-'3'

ml_driver_input$ID<-paste(ml_driver_input$Chromosome,ml_driver_input$Start_Position,ml_driver_input$End_Position,sep = "_")

#table(duplicated(ml_driver_input$ID))
ml_driver_input<-unique(ml_driver_input)
rownames(ml_driver_input)<-ml_driver_input$ID

ml_driver_input<-ml_driver_input[,c('Hugo_Symbol',"Variant_Classification",'sift')]
colnames(ml_driver_input)<-c("GENE_NAME","Mutation.Description.AA","MIN_SIFT_PRED")


cgc_tier1<-ml_driver_input
cgc_tier1$entrez<- mapIds(org.Hs.eg.db,
                          keys=cgc_tier1$GENE_NAME,
                          column="ENTREZID",
                          keytype="SYMBOL",)
cgc_tier1<-cgc_tier1[!is.na(cgc_tier1$entrez),]

cgc_tier1_kegg <- data.frame(matrix(ncol=length(kegg_name),nrow=nrow(cgc_tier1)))

colnames(cgc_tier1_kegg)<-kegg_name
cgc_tier1_kegg<-cbind(cgc_tier1,cgc_tier1_kegg)
for (i in 1:nrow(cgc_tier1_kegg)) {
  kegg_name_per_gene <- names(list.search(gene_list,as.character(cgc_tier1_kegg$entrez[i]) %in% .))
  cgc_tier1_kegg[i,kegg_name_per_gene] <-1
}
cgc_tier1_kegg[is.na(cgc_tier1_kegg)] <- 0
#sum(cgc_tier1_kegg[,10:(ncol(cgc_tier1_kegg)-1)])
cgc_tier1_kegg<-cgc_tier1_kegg[,-which(colnames(cgc_tier1) %in%c("GENE_NAME","entrez","X","CGC_TIER","Mutation.Description.CDS"))]

write.csv(cgc_tier1,paste0(inputMAF[1],".mutations.csv"))
write.csv(cgc_tier1_kegg,paste0(inputMAF[1],'.feature.matrix.csv'))
